DO $$
BEGIN
  CREATE TYPE "CareLevel" AS ENUM ('PREVENTATIVE', 'DEMENTIA');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

ALTER TABLE "patients"
ADD COLUMN IF NOT EXISTS "care_level" "CareLevel" NOT NULL DEFAULT 'DEMENTIA',
ADD COLUMN IF NOT EXISTS "ai_adaptive_enabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "success_rate" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "ai_difficulty_model" JSONB;

ALTER TABLE "quiz_attempts"
ADD COLUMN IF NOT EXISTS "difficulty" TEXT,
ADD COLUMN IF NOT EXISTS "question_mode" TEXT,
ADD COLUMN IF NOT EXISTS "had_hint" BOOLEAN NOT NULL DEFAULT false;
